### ISSUE TITLE
Module's report on exceptions is useless

### ISSUE THREAD

**Issue by vrurg** [tony-o/perl6-pluggable#10]
If an exception happens in `require` (due to a syntax or other error) then module's messages tells nothing about the source of the problem. This is what I get:

`X::AdHoc(SETTING::src/core/Exception.pm6 57 throw)`

**Comment by tony-o** [comment]
@vrurg `$*DEBUG-PLUGINS` is an option that is checked and will output the full error if set to a truthy value.  see `t/04-syntax-error.t` for an example.  This is implemented in a13289f

**Comment by vrurg** [comment]
It would be nice to have it documented, perhaps. But anyway – thank you!

**Comment by tony-o** [comment]
You're right, I'll add that to the readme.  Thank you for the report @vrurg
