### ISSUE TITLE
@*INC is no longer available

### ISSUE THREAD

**Issue by zoffixznet** [tony-o/perl6-pluggable#5]
On newest Rakudo this module is broken because @*INC was removed.

~~While currently there's no solution, it might be easy to bring back the ability to look up modules the way needed for this module. See http://irclog.perlgeek.de/perl6/2015-12-01#i_11634431~~ **Feb 2017 edit:** that statement might not be accurate any more; see https://irclog.perlgeek.de/perl6/2017-02-24#i_14158644

**Comment by tony-o** [comment]
check out the new version -
